services:
  app:
    build: .
    image: ${OKTETO_BUILD_FRONTEND_IMAGE}
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    labels:
      dev.okteto.com/service-type: NodePort
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:001218795811:certificate/6b3c8aae-12b7-4a44-8960-bcb3a3fcefe5